In [32]:
import requests
import pandas as pd
import os, sys
import time
from tqdm import tqdm_notebook

In [23]:
# Load API key
API_KEY = "e72f9f9d5011325e78ac58c5736911857607"

In [80]:
# TODO: Modify to point to a file hosted in the ComptoxAI repository with relative path
# Note: These are MeSH identifiers. We use Entrez to map them as a SourceID to PubChem identifiers instead
mesh_ids_file = "~/data/ctdbase/ctd_chemical_identifiers.txt"

chemical_mapping = pd.read_csv(mesh_ids_file, header=None)

In [81]:
chemical_mapping.columns = ['mesh']

In [82]:
chemical_mapping['pubchem_cid'] = None
chemical_mapping['pubchem_sid'] = None
chemical_mapping['casrn'] = None
chemical_mapping['dtxsid'] = None

In [83]:
chemical_mapping

              mesh pubchem_cid pubchem_sid casrn dtxsid
0          C089250        None        None  None   None
1          C114385        None        None  None   None
2          C114386        None        None  None   None
3          C434150        None        None  None   None
4          C434149        None        None  None   None
...            ...         ...         ...   ...    ...
176066     C482761        None        None  None   None
176067  C000712888        None        None  None   None
176068     C558532        None        None  None   None
176069     C483463        None        None  None   None
176070     C558533        None        None  None   None

[176071 rows x 5 columns]

In [84]:
chemical_mapping_test = chemical_mapping.head(n=27)

In [92]:
BASE_URL = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi'

def get_pubchem_sid(mesh_id):
    payload = {
        'db': 'pcsubstance',
        'term': f"{mesh_id}[SourceID]",
        'retmode': 'json',
        'api_key': API_KEY
    }
    r = requests.post(url=BASE_URL, params=payload)
    try:
        return r.json()['esearchresult']['idlist']
    except:
        return []

for i, m in enumerate(tqdm_notebook(chemical_mapping['mesh'])):
    sid_col_idx = chemical_mapping.columns.get_loc('pubchem_sid')
    sid = get_pubchem_cid(m)
    assert(len(cid) < 2)

    if len(cid) == 1:
        cid = cid[0]
        chemical_mapping_test.iloc[i, sid_col_idx] = cid

    if i%10 == 0:
        time.sleep(0.1)

/var/folders/mb/jkjn3zh97jz9dbxlswr4mj8c0000gn/T/ipykernel_88309/134363505.py:16: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i, m in enumerate(tqdm_notebook(chemical_mapping['mesh'])):

  0%|          | 0/176071 [00:00<?, ?it/s]

KeyboardInterrupt:

In [90]:
chemical_mapping_test

          mesh pubchem_cid pubchem_sid casrn dtxsid
0      C089250        None        None  None   None
1      C114385        None        None  None   None
2      C114386        None        None  None   None
3      C434150        None        None  None   None
4      C434149        None        None  None   None
5   C000620092        None        None  None   None
6      C533344        None        None  None   None
7      C533345        None        None  None   None
8      C046983   134223433   134223433  None   None
9      C585814        None        None  None   None
10     C533898        None        None  None   None
11     C493119        None        None  None   None
12     C014305        None        None  None   None
13     C473129        None        None  None   None
14     C534883   252090125   252090125  None   None
15     C093446        None        None  None   None
16     C112297    85177289    85177289  None   None
17     C024526   478116267   478116267  None   None
18     C053260        None        None  None   None
19     C060259        None        None  None   None
20     C040211   478128371   478128371  None   None
21     C033472   478122095   478122095  None   None
22  C000599298        None        None  None   None
23  C000598765        None        None  None   None
24     C038721   478124193   478124193  None   None
25     C421343        None        None  None   None
26  C000604906        None        None  None   None